### ISSUE TITLE
Version 3.5: Images broken in Chrome

### ISSUE THREAD

**Issue by delwaterman** [joesinghaus/Blades-in-the-Dark#3]
<img width="327" alt="screen shot 2018-05-22 at 1 11 45 pm" src="https://user-images.githubusercontent.com/70605/40378507-c471df04-5dc1-11e8-8c00-5e444abd0712.png">

**Comment by joesinghaus** [comment]
I'm looking at it in Chrome right now and it seems to work. Does this issue persist for you?

**Comment by delwaterman** [comment]
@joesinghaus yeah still broken for me. Maybe something broke when the sheet upgraded?

Chrome:
Version 66.0.3359.181 (Official Build) (64-bit)
 OS X

**Comment by joesinghaus** [comment]
I have the exact same browser, version, and OS. Have you tried clearing your cache?

If clearing the cache doesn't work, it might be a problem for you with Roll20's image server, or with your ISP, perhaps?

**Comment by delwaterman** [comment]
I tried clearing cache, and that didn't work. Looking at the broken images in the chat I get this URL: http://imgsrv.roll20.net/?src=raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Blades%2520in%2520the%2520Dark/Assets/rolltemplate/rolltemplate-title-fortune.png What's weird is that if I open the image url in a separate tab, it opens correctly without issue. 

I just opened it an incognito browser and it loads the images correctly. So it has to be something in my browser, but I have no idea why clearing the cache wouldn't work. Hard refresh doesn't work. It's super weird. I guess this is just some super strange bug in chrome that I hit

**Comment by joesinghaus** [comment]
Huh, that's really odd. If that doesn't work, I'm out of ideas (except deleting your Chrome user config and perhaps reinstalling Chrome, maybe?). Anyway, it's definitely a local issue since you can open it incognito, so I'm going to close this issue.

Jakob

**Comment by delwaterman** [comment]
just to be sure I am going to load from another mac. Wonder if its my chrome profile

**Comment by delwaterman** [comment]
Yeah from a totally different laptop, same chrome profile, it works correctly. I will reboot the other machine see if that solves anything. thanks for your help with this.

**Comment by joesinghaus** [comment]
Glad to help. Good luck getting your laptop to see the images again!
